// J40 full vehicle CAD scaffold Rev A
// Units: millimetres. Coordinate system: X front to rear, Y centreline left/right, Z ground up.
// Generated by tools/generate_j40_full_vehicle_cad_scaffold.py.
// This is a project-owned reference scaffold, not a direct extraction of the licensed mesh.

$fn = 64;

module box_part(x, y_center, z, length, width, height) {
  translate([x, y_center - width / 2, z]) cube([length, width, height], center = false);
}

module wheel_part(x, y_center, z, diameter, width) {
  color([0.03, 0.03, 0.03, 1.0])
    translate([x, y_center, z]) rotate([90, 0, 0]) cylinder(d = diameter, h = width, center = true);
  color([0.72, 0.72, 0.72, 1.0])
    translate([x, y_center, z]) rotate([90, 0, 0]) cylinder(d = diameter * 0.52, h = width + 8, center = true);
  color([0.10, 0.10, 0.10, 1.0])
    translate([x, y_center, z]) rotate([90, 0, 0]) cylinder(d = diameter * 0.30, h = width + 14, center = true);
}

module cylinder_part(x, y, z, axis, diameter, length) {
  translate([x, y, z])
    if (axis == "x") rotate([0, 90, 0]) cylinder(d = diameter, h = length, center = true);
    else if (axis == "y") rotate([90, 0, 0]) cylinder(d = diameter, h = length, center = true);
    else cylinder(d = diameter, h = length, center = true);
}

// chassis: left_frame_rail - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(360, -390, 430, 3140, 85, 120);

// chassis: right_frame_rail - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(360, 390, 430, 3140, 85, 120);

// chassis: crossmember_1 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(450, 0, 455, 85, 880, 95);

// chassis: crossmember_2 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(980, 0, 455, 85, 880, 95);

// chassis: crossmember_3 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(1660, 0, 455, 85, 880, 95);

// chassis: crossmember_4 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(2420, 0, 455, 85, 880, 95);

// chassis: crossmember_5 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(3230, 0, 455, 85, 880, 95);

// chassis: front_bumper - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(20, 0, 525, 165, 1620, 120);

// chassis: rear_bumper - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(3665, 0, 530, 145, 1550, 110);

// chassis: front_left_tow_ring - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(75, -430, 450, "x", 115, 28);

// chassis: front_right_tow_ring - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(75, 430, 450, "x", 115, 28);

// running_gear: front_axle_tube - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(735, 0, 395, 90, 1560, 90);

// running_gear: rear_axle_tube - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(3020, 0, 395, 90, 1560, 90);

// running_gear: front_left_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, -430, 335, 1050, 65, 55);

// running_gear: front_right_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, 430, 335, 1050, 65, 55);

// running_gear: rear_left_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, -430, 335, 1050, 65, 55);

// running_gear: rear_right_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, 430, 335, 1050, 65, 55);

// running_gear: front_left_tire - L0 envelope
wheel_part(735, -705, 395, 790, 250);

// running_gear: front_right_tire - L0 envelope
wheel_part(735, 705, 395, 790, 250);

// running_gear: rear_left_tire - L0 envelope
wheel_part(3020, -705, 395, 790, 250);

// running_gear: rear_right_tire - L0 envelope
wheel_part(3020, 705, 395, 790, 250);

// running_gear: front_left_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(920, -520, 620, "z", 58, 460);

// running_gear: front_right_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(920, 520, 620, "z", 58, 460);

// running_gear: front_left_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, -840, 395, "y", 220, 80);

// running_gear: front_right_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, 840, 395, "y", 220, 80);

// running_gear: rear_left_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3205, -520, 620, "z", 58, 460);

// running_gear: rear_right_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3205, 520, 620, "z", 58, 460);

// running_gear: rear_left_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, -840, 395, "y", 220, 80);

// running_gear: rear_right_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, 840, 395, "y", 220, 80);

// body: floor_pan - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(890, 0, 615, 2550, 1330, 55);

// body: left_rocker_sill - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(1000, -720, 665, 2050, 95, 155);

// body: right_rocker_sill - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(1000, 720, 665, 2050, 95, 155);

// body: left_rear_quarter_panel - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(2140, -760, 725, 1270, 70, 610);

// body: right_rear_quarter_panel - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(2140, 760, 725, 1270, 70, 610);

// body: tailgate_panel - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(3400, 0, 720, 70, 1430, 650);

// body: firewall - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(1135, 0, 690, 80, 1420, 780);

// body: cowl_top - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(1085, 0, 1260, 190, 1460, 110);

// body: grille_panel - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(170, 0, 790, 80, 1410, 520);

// front_detail: white_grille_surround - L0 envelope
color([0.910, 0.910, 0.910, 0.80])
  box_part(125, 0, 795, 35, 1120, 365);

// front_detail: black_grille_mesh - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(105, 0, 910, 30, 640, 155);

// front_detail: left_headlamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(92, -445, 985, "x", 225, 38);

// front_detail: right_headlamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(92, 445, 985, "x", 225, 38);

// front_detail: left_indicator_lamp - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(84, -720, 845, "x", 105, 30);

// front_detail: right_indicator_lamp - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(84, 720, 845, "x", 105, 30);

// front_detail: left_fog_lamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(25, -360, 620, "x", 165, 36);

// front_detail: right_fog_lamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(25, 360, 620, "x", 165, 36);

// body: hood_closed_reference - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(230, 0, 1215, 920, 1390, 55);

// body: hood_open_visual_reference - visual only
color([0.471, 0.725, 0.788, 0.80])
  box_part(420, 0, 1420, 1180, 1390, 35);

// body: hood_left_hinge_axis - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1030, -540, 1288, "y", 28, 230);

// body: hood_right_hinge_axis - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1030, 540, 1288, "y", 28, 230);

// body: left_front_fender - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(270, -720, 760, 860, 270, 260);

// body: right_front_fender - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(270, 720, 760, 860, 270, 260);

// body: left_inner_fender - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(290, -520, 800, 800, 70, 420);

// body: right_inner_fender - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(290, 520, 800, 800, 70, 420);

// body: windshield_frame - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(1155, 0, 1315, 80, 1480, 520);

// body: windshield_glass - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1160, 0, 1380, 35, 1300, 410);

// body: windshield_left_wiper - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1110, -250, 1370, "y", 24, 430);

// body: windshield_right_wiper - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1110, 250, 1370, "y", 24, 430);

// soft_top: canvas_roof - L0 envelope
color([0.847, 0.765, 0.647, 0.80])
  box_part(1210, 0, 1845, 2290, 1540, 100);

// soft_top: left_canvas_side - L0 envelope
color([0.847, 0.765, 0.647, 0.80])
  box_part(1240, -790, 1320, 2200, 55, 590);

// soft_top: right_canvas_side - L0 envelope
color([0.847, 0.765, 0.647, 0.80])
  box_part(1240, 790, 1320, 2200, 55, 590);

// soft_top: left_front_canvas_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1370, -823, 1430, 500, 18, 320);

// soft_top: left_rear_canvas_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(2120, -823, 1430, 610, 18, 320);

// soft_top: right_front_canvas_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1370, 823, 1430, 500, 18, 320);

// soft_top: right_rear_canvas_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(2120, 823, 1430, 610, 18, 320);

// soft_top: rear_canvas_panel - L0 envelope
color([0.847, 0.765, 0.647, 0.80])
  box_part(3440, 0, 1320, 55, 1540, 590);

// soft_top: front_soft_top_bow - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1290, 0, 1740, 45, 1510, 75);

// soft_top: middle_soft_top_bow - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1960, 0, 1740, 45, 1510, 75);

// soft_top: rear_soft_top_bow - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(2640, 0, 1740, 45, 1510, 75);

// soft_top: left_canvas_tie_down_1 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(1460, -835, 1180, 35, 26, 105);

// soft_top: right_canvas_tie_down_1 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(1460, 835, 1180, 35, 26, 105);

// soft_top: left_canvas_tie_down_2 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(1740, -835, 1180, 35, 26, 105);

// soft_top: right_canvas_tie_down_2 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(1740, 835, 1180, 35, 26, 105);

// soft_top: left_canvas_tie_down_3 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2020, -835, 1180, 35, 26, 105);

// soft_top: right_canvas_tie_down_3 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2020, 835, 1180, 35, 26, 105);

// soft_top: left_canvas_tie_down_4 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2300, -835, 1180, 35, 26, 105);

// soft_top: right_canvas_tie_down_4 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2300, 835, 1180, 35, 26, 105);

// soft_top: left_canvas_tie_down_5 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2580, -835, 1180, 35, 26, 105);

// soft_top: right_canvas_tie_down_5 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2580, 835, 1180, 35, 26, 105);

// soft_top: left_canvas_tie_down_6 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2860, -835, 1180, 35, 26, 105);

// soft_top: right_canvas_tie_down_6 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(2860, 835, 1180, 35, 26, 105);

// soft_top: left_canvas_tie_down_7 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(3140, -835, 1180, 35, 26, 105);

// soft_top: right_canvas_tie_down_7 - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(3140, 835, 1180, 35, 26, 105);

// body: left_door_open_reference - visual only
color([0.471, 0.725, 0.788, 0.80])
  box_part(1180, -910, 760, 800, 70, 850);

// body: right_door_closed_reference - L0 envelope
color([0.471, 0.725, 0.788, 0.80])
  box_part(1180, 760, 760, 800, 70, 850);

// body: left_door_window_glass - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1280, -948, 1210, 520, 22, 345);

// body: right_door_window_glass - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1280, 798, 1210, 520, 22, 345);

// body: left_upper_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, -955, 1180, "z", 38, 145);

// body: left_lower_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, -955, 850, "z", 38, 145);

// body: right_upper_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, 805, 1180, "z", 38, 145);

// body: right_lower_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, 805, 850, "z", 38, 145);

// body: left_door_handle - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1575, -955, 1045, 160, 30, 40);

// body: right_door_handle - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1575, 805, 1045, 160, 30, 40);

// engine_bay: engine_block - L0 envelope
color([0.247, 0.259, 0.271, 0.80])
  box_part(460, 0, 720, 520, 420, 430);

// engine_bay: valve_cover - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(510, 0, 1080, 460, 180, 70);

// engine_bay: radiator - L0 envelope
color([0.247, 0.259, 0.271, 0.80])
  box_part(235, 0, 820, 75, 980, 520);

// engine_bay: air_filter - L0 envelope
color([0.247, 0.259, 0.271, 0.80])
  box_part(760, -235, 1120, 210, 210, 150);

// engine_bay: battery_tray_reference - L0 envelope
color([0.910, 0.910, 0.910, 0.80])
  box_part(600, 430, 760, 330, 220, 220);

// engine_bay: inline_six_intake_stack_1 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, -165, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_2 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, -99, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_3 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, -33, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_4 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, 33, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_5 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, 99, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_6 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, 165, 1160, "z", 46, 180);

// engine_bay: upper_radiator_hose - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(330, -185, 1110, "x", 72, 430);

// engine_bay: exhaust_downpipe_reference - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(615, 255, 845, "z", 82, 460);

// interior: dashboard - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1235, 0, 1080, 120, 1320, 220);

// interior: steering_column - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1315, -360, 935, 520, 60, 60);

// interior: steering_wheel - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1240, -420, 1210, "x", 380, 32);

// interior: steering_wheel_hub - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1230, -420, 1210, "x", 135, 55);

// interior: dashboard_gauge_1 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -560, 1175, "x", 72, 24);

// interior: dashboard_gauge_2 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -470, 1175, "x", 72, 24);

// interior: dashboard_gauge_3 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -380, 1175, "x", 72, 24);

// interior: dashboard_gauge_4 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -290, 1175, "x", 72, 24);

// interior: transfer_case_lever - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1580, -120, 820, "z", 36, 285);

// interior: gearshift_lever - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1500, -35, 820, "z", 38, 330);

// interior: front_left_seat_base - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1660, -310, 700, 420, 410, 130);

// interior: front_left_seat_back - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1850, -310, 820, 95, 410, 620);

// interior: front_left_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(1905, -310, 1435, "y", 150, 300);

// interior: front_right_seat_base - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1660, 310, 700, 420, 410, 130);

// interior: front_right_seat_back - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1850, 310, 820, 95, 410, 620);

// interior: front_right_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(1905, 310, 1435, "y", 150, 300);

// interior: rear_bench_base - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(2510, 0, 720, 610, 1080, 135);

// interior: rear_bench_back - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(2920, 0, 840, 105, 1080, 560);

// interior: rear_bench_left_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(2975, -350, 1390, "y", 140, 270);

// interior: rear_bench_right_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(2975, 350, 1390, "y", 140, 270);
