// J40 full vehicle CAD scaffold Rev B
// Units: millimetres. Coordinate system: X front to rear, Y centreline left/right, Z ground up.
// Left-hand drive: negative Y is the driver side.
// Generated by tools/generate_j40_full_vehicle_cad_scaffold.py.
// This is a project-owned reference scaffold, not a direct extraction of the CC-BY mesh.

$fn = 64;

module box_part(x, y_center, z, length, width, height) {
  translate([x, y_center - width / 2, z]) cube([length, width, height], center = false);
}

module wheel_part(x, y_center, z, diameter, width) {
  color([0.03, 0.03, 0.03, 1.0])
    translate([x, y_center, z]) rotate([90, 0, 0]) cylinder(d = diameter, h = width, center = true);
  color([0.72, 0.72, 0.72, 1.0])
    translate([x, y_center, z]) rotate([90, 0, 0]) cylinder(d = diameter * 0.52, h = width + 8, center = true);
  color([0.10, 0.10, 0.10, 1.0])
    translate([x, y_center, z]) rotate([90, 0, 0]) cylinder(d = diameter * 0.30, h = width + 14, center = true);
}

module cylinder_part(x, y, z, axis, diameter, length) {
  translate([x, y, z])
    if (axis == "x") rotate([0, 90, 0]) cylinder(d = diameter, h = length, center = true);
    else if (axis == "y") rotate([90, 0, 0]) cylinder(d = diameter, h = length, center = true);
    else cylinder(d = diameter, h = length, center = true);
}

// chassis: left_frame_rail - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(360, -390, 430, 3140, 85, 120);

// chassis: right_frame_rail - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(360, 390, 430, 3140, 85, 120);

// chassis: crossmember_1 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(450, 0, 455, 85, 880, 95);

// chassis: crossmember_2 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(980, 0, 455, 85, 880, 95);

// chassis: crossmember_3 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(1660, 0, 455, 85, 880, 95);

// chassis: crossmember_4 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(2420, 0, 455, 85, 880, 95);

// chassis: crossmember_5 - L0 envelope
color([0.176, 0.188, 0.200, 0.80])
  box_part(3230, 0, 455, 85, 880, 95);

// chassis: front_bumper - L0 envelope
color([0.067, 0.075, 0.082, 0.80])
  box_part(20, 0, 525, 165, 1620, 120);

// chassis: rear_bumper - L0 envelope
color([0.067, 0.075, 0.082, 0.80])
  box_part(3665, 0, 530, 145, 1550, 110);

// chassis: front_left_tow_ring - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(75, -430, 450, "x", 115, 28);

// chassis: front_right_tow_ring - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(75, 430, 450, "x", 115, 28);

// running_gear: front_axle_tube - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(735, 0, 395, 90, 1560, 90);

// running_gear: rear_axle_tube - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(3020, 0, 395, 90, 1560, 90);

// running_gear: front_left_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, -430, 335, 1050, 65, 55);

// running_gear: front_right_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, 430, 335, 1050, 65, 55);

// running_gear: rear_left_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, -430, 335, 1050, 65, 55);

// running_gear: rear_right_leaf_spring - L0 envelope
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, 430, 335, 1050, 65, 55);

// running_gear: front_left_tire - L0 envelope
wheel_part(735, -705, 395, 790, 250);

// running_gear: front_right_tire - L0 envelope
wheel_part(735, 705, 395, 790, 250);

// running_gear: rear_left_tire - L0 envelope
wheel_part(3020, -705, 395, 790, 250);

// running_gear: rear_right_tire - L0 envelope
wheel_part(3020, 705, 395, 790, 250);

// running_gear: front_left_mud_tire_outer_lug_1 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1110, -705, 395, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_2 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1081.45, -705, 538.506, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_3 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1000.17, -705, 660.165, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_4 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(878.506, -705, 741.455, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_5 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(735, -705, 770, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_6 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(591.494, -705, 741.455, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_7 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(469.835, -705, 660.165, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_8 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(388.545, -705, 538.506, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_9 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(360, -705, 395, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_10 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(388.545, -705, 251.494, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_11 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(469.835, -705, 129.835, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_12 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(591.494, -705, 48.5452, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_13 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(735, -705, 20, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_14 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(878.506, -705, 48.5452, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_15 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1000.17, -705, 129.835, 95, 48, 58);

// running_gear: front_left_mud_tire_outer_lug_16 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1081.45, -705, 251.494, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_1 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1110, 705, 395, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_2 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1081.45, 705, 538.506, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_3 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1000.17, 705, 660.165, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_4 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(878.506, 705, 741.455, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_5 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(735, 705, 770, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_6 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(591.494, 705, 741.455, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_7 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(469.835, 705, 660.165, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_8 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(388.545, 705, 538.506, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_9 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(360, 705, 395, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_10 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(388.545, 705, 251.494, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_11 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(469.835, 705, 129.835, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_12 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(591.494, 705, 48.5452, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_13 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(735, 705, 20, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_14 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(878.506, 705, 48.5452, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_15 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1000.17, 705, 129.835, 95, 48, 58);

// running_gear: front_right_mud_tire_outer_lug_16 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1081.45, 705, 251.494, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_1 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3395, -705, 395, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_2 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3366.45, -705, 538.506, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_3 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3285.17, -705, 660.165, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_4 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3163.51, -705, 741.455, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_5 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3020, -705, 770, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_6 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2876.49, -705, 741.455, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_7 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2754.83, -705, 660.165, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_8 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2673.55, -705, 538.506, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_9 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2645, -705, 395, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_10 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2673.55, -705, 251.494, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_11 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2754.83, -705, 129.835, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_12 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2876.49, -705, 48.5452, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_13 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3020, -705, 20, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_14 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3163.51, -705, 48.5452, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_15 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3285.17, -705, 129.835, 95, 48, 58);

// running_gear: rear_left_mud_tire_outer_lug_16 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3366.45, -705, 251.494, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_1 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3395, 705, 395, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_2 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3366.45, 705, 538.506, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_3 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3285.17, 705, 660.165, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_4 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3163.51, 705, 741.455, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_5 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3020, 705, 770, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_6 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2876.49, 705, 741.455, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_7 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2754.83, 705, 660.165, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_8 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2673.55, 705, 538.506, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_9 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2645, 705, 395, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_10 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2673.55, 705, 251.494, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_11 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2754.83, 705, 129.835, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_12 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2876.49, 705, 48.5452, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_13 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3020, 705, 20, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_14 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3163.51, 705, 48.5452, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_15 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3285.17, 705, 129.835, 95, 48, 58);

// running_gear: rear_right_mud_tire_outer_lug_16 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3366.45, 705, 251.494, 95, 48, 58);

// running_gear: front_left_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(920, -520, 620, "z", 58, 460);

// running_gear: front_right_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(920, 520, 620, "z", 58, 460);

// running_gear: front_left_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, -840, 395, "y", 220, 80);

// running_gear: front_right_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, 840, 395, "y", 220, 80);

// running_gear: rear_left_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3205, -520, 620, "z", 58, 460);

// running_gear: rear_right_shock_body - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3205, 520, 620, "z", 58, 460);

// running_gear: rear_left_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, -840, 395, "y", 220, 80);

// running_gear: rear_right_hub_cap - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, 840, 395, "y", 220, 80);

// body: floor_pan - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(890, 0, 615, 2550, 1330, 55);

// body: left_rocker_sill - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1000, -720, 665, 2050, 95, 155);

// body: right_rocker_sill - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1000, 720, 665, 2050, 95, 155);

// body: left_rear_quarter_panel - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(2140, -760, 725, 1270, 70, 610);

// body: right_rear_quarter_panel - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(2140, 760, 725, 1270, 70, 610);

// body: tailgate_panel - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(3400, 0, 720, 70, 1430, 650);

// body: firewall - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1135, 0, 690, 80, 1420, 780);

// body: cowl_top - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1085, 0, 1260, 190, 1460, 110);

// body: grille_panel - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(170, 0, 790, 80, 1410, 520);

// front_detail: white_grille_surround - L0 envelope
color([0.910, 0.910, 0.910, 0.80])
  box_part(125, 0, 795, 35, 1120, 365);

// front_detail: black_grille_mesh - L0 envelope
color([0.114, 0.114, 0.114, 0.80])
  box_part(105, 0, 910, 30, 640, 155);

// front_detail: left_headlamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(92, -445, 985, "x", 225, 38);

// front_detail: right_headlamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(92, 445, 985, "x", 225, 38);

// front_detail: left_indicator_lamp - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(84, -720, 845, "x", 105, 30);

// front_detail: right_indicator_lamp - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(84, 720, 845, "x", 105, 30);

// front_detail: left_fog_lamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(25, -360, 620, "x", 165, 36);

// front_detail: right_fog_lamp - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(25, 360, 620, "x", 165, 36);

// body: hood_closed_reference - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(230, 0, 1215, 920, 1390, 55);

// body: hood_open_visual_reference - visual only
color([0.812, 0.776, 0.667, 0.80])
  box_part(420, 0, 1420, 1180, 1390, 35);

// body: hood_left_hinge_axis - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1030, -540, 1288, "y", 28, 230);

// body: hood_right_hinge_axis - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1030, 540, 1288, "y", 28, 230);

// body: left_front_fender - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(270, -720, 760, 860, 270, 260);

// body: right_front_fender - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(270, 720, 760, 860, 270, 260);

// body: left_inner_fender - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(290, -520, 800, 800, 70, 420);

// body: right_inner_fender - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(290, 520, 800, 800, 70, 420);

// body: windshield_frame - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1155, 0, 1315, 80, 1480, 520);

// body: windshield_glass - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1160, 0, 1380, 35, 1300, 410);

// body: windshield_left_wiper - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1110, -250, 1370, "y", 24, 430);

// body: windshield_right_wiper - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1110, 250, 1370, "y", 24, 430);

// hard_top: white_hardtop_roof - L0 envelope
color([0.945, 0.933, 0.894, 0.80])
  box_part(1210, 0, 1845, 2290, 1540, 110);

// hard_top: left_hardtop_side_panel - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1240, -790, 1320, 2200, 55, 590);

// hard_top: right_hardtop_side_panel - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1240, 790, 1320, 2200, 55, 590);

// hard_top: left_front_hardtop_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1420, -823, 1435, 500, 20, 320);

// hard_top: left_rear_hardtop_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(2190, -823, 1435, 610, 20, 320);

// hard_top: right_front_hardtop_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1420, 823, 1435, 500, 20, 320);

// hard_top: right_rear_hardtop_window - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(2190, 823, 1435, 610, 20, 320);

// hard_top: rear_hardtop_panel - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(3440, 0, 1320, 55, 1540, 590);

// hard_top: roof_front_gutter - L0 envelope
color([0.945, 0.933, 0.894, 0.80])
  box_part(1160, 0, 1810, 70, 1575, 46);

// hard_top: roof_left_gutter - L0 envelope
color([0.945, 0.933, 0.894, 0.80])
  box_part(2250, -830, 1815, 2200, 58, 42);

// hard_top: roof_right_gutter - L0 envelope
color([0.945, 0.933, 0.894, 0.80])
  box_part(2250, 830, 1815, 2200, 58, 42);

// body: left_door_open_reference - visual only
color([0.812, 0.776, 0.667, 0.80])
  box_part(1180, -910, 760, 800, 70, 850);

// body: right_door_closed_reference - L0 envelope
color([0.812, 0.776, 0.667, 0.80])
  box_part(1180, 760, 760, 800, 70, 850);

// body: left_door_window_glass - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1280, -948, 1210, 520, 22, 345);

// body: right_door_window_glass - L0 envelope
color([0.435, 0.647, 0.722, 0.80])
  box_part(1280, 798, 1210, 520, 22, 345);

// body: left_upper_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, -955, 1180, "z", 38, 145);

// body: left_lower_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, -955, 850, "z", 38, 145);

// body: right_upper_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, 805, 1180, "z", 38, 145);

// body: right_lower_door_hinge - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1135, 805, 850, "z", 38, 145);

// body: left_door_handle - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1575, -955, 1045, 160, 30, 40);

// body: right_door_handle - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1575, 805, 1045, 160, 30, 40);

// engine_bay: engine_block - L0 envelope
color([0.247, 0.259, 0.271, 0.80])
  box_part(460, 0, 720, 520, 420, 430);

// engine_bay: valve_cover - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(510, 0, 1080, 460, 180, 70);

// engine_bay: radiator - L0 envelope
color([0.247, 0.259, 0.271, 0.80])
  box_part(235, 0, 820, 75, 980, 520);

// engine_bay: air_filter - L0 envelope
color([0.247, 0.259, 0.271, 0.80])
  box_part(760, -235, 1120, 210, 210, 150);

// engine_bay: battery_tray_reference - L0 envelope
color([0.910, 0.910, 0.910, 0.80])
  box_part(600, 430, 760, 330, 220, 220);

// engine_bay: inline_six_intake_stack_1 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, -165, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_2 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, -99, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_3 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, -33, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_4 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, 33, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_5 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, 99, 1160, "z", 46, 180);

// engine_bay: inline_six_intake_stack_6 - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(470, 165, 1160, "z", 46, 180);

// engine_bay: upper_radiator_hose - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(330, -185, 1110, "x", 72, 430);

// engine_bay: exhaust_downpipe_reference - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(615, 255, 845, "z", 82, 460);

// interior: dashboard - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1235, 0, 1080, 120, 1320, 220);

// interior: steering_column - L0 envelope
color([0.722, 0.722, 0.722, 0.80])
  box_part(1135, -420, 935, 590, 60, 60);

// interior: steering_wheel - L1 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1240, -420, 1210, "x", 380, 32);

// interior: steering_wheel_hub - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1230, -420, 1210, "x", 135, 55);

// interior: dashboard_gauge_1 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -560, 1175, "x", 72, 24);

// interior: dashboard_gauge_2 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -470, 1175, "x", 72, 24);

// interior: dashboard_gauge_3 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -380, 1175, "x", 72, 24);

// interior: dashboard_gauge_4 - L1 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(1222, -290, 1175, "x", 72, 24);

// interior: transfer_case_lever - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1580, -120, 820, "z", 36, 285);

// interior: gearshift_lever - L1 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1500, -35, 820, "z", 38, 330);

// interior: front_left_seat_base - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1660, -310, 700, 420, 410, 130);

// interior: front_left_seat_back - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1850, -310, 820, 95, 410, 620);

// interior: front_left_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(1905, -310, 1435, "y", 150, 300);

// interior: front_right_seat_base - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1660, 310, 700, 420, 410, 130);

// interior: front_right_seat_back - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(1850, 310, 820, 95, 410, 620);

// interior: front_right_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(1905, 310, 1435, "y", 150, 300);

// interior: rear_bench_base - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(2510, 0, 720, 610, 1080, 135);

// interior: rear_bench_back - L0 envelope
color([0.722, 0.482, 0.333, 0.80])
  box_part(2920, 0, 840, 105, 1080, 560);

// interior: rear_bench_left_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(2975, -350, 1390, "y", 140, 270);

// interior: rear_bench_right_headrest - L1 visible-detail primitive
color([0.722, 0.482, 0.333, 0.80])
  cylinder_part(2975, 350, 1390, "y", 140, 270);

// chassis: left_front_frame_horn_top_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(120, -390, 555, 500, 95, 24);

// chassis: left_front_frame_horn_side_web - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(120, -448, 440, 500, 18, 150);

// chassis: left_rear_frame_horn_top_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3230, -390, 555, 420, 95, 24);

// chassis: left_rear_frame_horn_side_web - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3230, -448, 440, 420, 18, 145);

// chassis: left_body_mount_outrigger_1 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(740, -525, 525, 280, 70, 55);

// chassis: left_body_mount_rubber_biscuit_1 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(965, -615, 610, "z", 118, 42);

// chassis: left_body_mount_center_bolt_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(965, -615, 632, "z", 30, 70);

// chassis: left_body_mount_outrigger_2 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1135, -525, 525, 280, 70, 55);

// chassis: left_body_mount_rubber_biscuit_2 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1360, -615, 610, "z", 118, 42);

// chassis: left_body_mount_center_bolt_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1360, -615, 632, "z", 30, 70);

// chassis: left_body_mount_outrigger_3 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1610, -525, 525, 280, 70, 55);

// chassis: left_body_mount_rubber_biscuit_3 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1835, -615, 610, "z", 118, 42);

// chassis: left_body_mount_center_bolt_3 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1835, -615, 632, "z", 30, 70);

// chassis: left_body_mount_outrigger_4 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2250, -525, 525, 280, 70, 55);

// chassis: left_body_mount_rubber_biscuit_4 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(2475, -615, 610, "z", 118, 42);

// chassis: left_body_mount_center_bolt_4 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2475, -615, 632, "z", 30, 70);

// chassis: left_body_mount_outrigger_5 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2920, -525, 525, 280, 70, 55);

// chassis: left_body_mount_rubber_biscuit_5 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(3145, -615, 610, "z", 118, 42);

// chassis: left_body_mount_center_bolt_5 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3145, -615, 632, "z", 30, 70);

// chassis: left_front_fixed_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(210, -475, 360, 105, 28, 180);

// chassis: left_front_fixed_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(210, -390, 360, 105, 28, 180);

// chassis: left_front_fixed_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(262, -432.5, 430, "y", 42, 130);

// chassis: left_front_shackle_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1280, -475, 360, 105, 28, 180);

// chassis: left_front_shackle_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1280, -390, 360, 105, 28, 180);

// chassis: left_front_shackle_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1332, -432.5, 430, "y", 42, 130);

// chassis: left_rear_fixed_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2495, -475, 360, 105, 28, 180);

// chassis: left_rear_fixed_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2495, -390, 360, 105, 28, 180);

// chassis: left_rear_fixed_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2547, -432.5, 430, "y", 42, 130);

// chassis: left_rear_shackle_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3565, -475, 360, 105, 28, 180);

// chassis: left_rear_shackle_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3565, -390, 360, 105, 28, 180);

// chassis: left_rear_shackle_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3617, -432.5, 430, "y", 42, 130);

// chassis: left_crossmember_1_gusset_front - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(898, -390, 465, 38, 230, 90);

// chassis: left_crossmember_1_gusset_rear - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1106, -390, 465, 38, 230, 90);

// chassis: left_crossmember_2_gusset_front - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1578, -390, 465, 38, 230, 90);

// chassis: left_crossmember_2_gusset_rear - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1786, -390, 465, 38, 230, 90);

// chassis: left_crossmember_3_gusset_front - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2338, -390, 465, 38, 230, 90);

// chassis: left_crossmember_3_gusset_rear - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2546, -390, 465, 38, 230, 90);

// running_gear: left_front_upper_shock_mount - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(945, -575, 875, 115, 110, 135);

// running_gear: left_rear_upper_shock_mount - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3185, -575, 875, 115, 110, 135);

// running_gear: left_front_shock_piston_rod - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(920, -520, 850, "z", 24, 280);

// running_gear: left_rear_shock_piston_rod - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3205, -520, 850, "z", 24, 280);

// running_gear: left_front_bump_stop - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(640, -495, 540, 115, 80, 72);

// running_gear: left_rear_bump_stop - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(2925, -495, 540, 115, 80, 72);

// chassis: right_front_frame_horn_top_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(120, 390, 555, 500, 95, 24);

// chassis: right_front_frame_horn_side_web - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(120, 448, 440, 500, 18, 150);

// chassis: right_rear_frame_horn_top_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3230, 390, 555, 420, 95, 24);

// chassis: right_rear_frame_horn_side_web - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3230, 448, 440, 420, 18, 145);

// chassis: right_body_mount_outrigger_1 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(740, 525, 525, 280, 70, 55);

// chassis: right_body_mount_rubber_biscuit_1 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(965, 615, 610, "z", 118, 42);

// chassis: right_body_mount_center_bolt_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(965, 615, 632, "z", 30, 70);

// chassis: right_body_mount_outrigger_2 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1135, 525, 525, 280, 70, 55);

// chassis: right_body_mount_rubber_biscuit_2 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1360, 615, 610, "z", 118, 42);

// chassis: right_body_mount_center_bolt_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1360, 615, 632, "z", 30, 70);

// chassis: right_body_mount_outrigger_3 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1610, 525, 525, 280, 70, 55);

// chassis: right_body_mount_rubber_biscuit_3 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1835, 615, 610, "z", 118, 42);

// chassis: right_body_mount_center_bolt_3 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1835, 615, 632, "z", 30, 70);

// chassis: right_body_mount_outrigger_4 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2250, 525, 525, 280, 70, 55);

// chassis: right_body_mount_rubber_biscuit_4 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(2475, 615, 610, "z", 118, 42);

// chassis: right_body_mount_center_bolt_4 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2475, 615, 632, "z", 30, 70);

// chassis: right_body_mount_outrigger_5 - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2920, 525, 525, 280, 70, 55);

// chassis: right_body_mount_rubber_biscuit_5 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(3145, 615, 610, "z", 118, 42);

// chassis: right_body_mount_center_bolt_5 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3145, 615, 632, "z", 30, 70);

// chassis: right_front_fixed_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(210, 475, 360, 105, 28, 180);

// chassis: right_front_fixed_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(210, 390, 360, 105, 28, 180);

// chassis: right_front_fixed_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(262, 432.5, 430, "y", 42, 130);

// chassis: right_front_shackle_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1280, 475, 360, 105, 28, 180);

// chassis: right_front_shackle_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1280, 390, 360, 105, 28, 180);

// chassis: right_front_shackle_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1332, 432.5, 430, "y", 42, 130);

// chassis: right_rear_fixed_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2495, 475, 360, 105, 28, 180);

// chassis: right_rear_fixed_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2495, 390, 360, 105, 28, 180);

// chassis: right_rear_fixed_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2547, 432.5, 430, "y", 42, 130);

// chassis: right_rear_shackle_spring_hanger_outer_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3565, 475, 360, 105, 28, 180);

// chassis: right_rear_shackle_spring_hanger_inner_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3565, 390, 360, 105, 28, 180);

// chassis: right_rear_shackle_spring_pin - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3617, 432.5, 430, "y", 42, 130);

// chassis: right_crossmember_1_gusset_front - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(898, 390, 465, 38, 230, 90);

// chassis: right_crossmember_1_gusset_rear - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1106, 390, 465, 38, 230, 90);

// chassis: right_crossmember_2_gusset_front - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1578, 390, 465, 38, 230, 90);

// chassis: right_crossmember_2_gusset_rear - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1786, 390, 465, 38, 230, 90);

// chassis: right_crossmember_3_gusset_front - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2338, 390, 465, 38, 230, 90);

// chassis: right_crossmember_3_gusset_rear - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(2546, 390, 465, 38, 230, 90);

// running_gear: right_front_upper_shock_mount - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(945, 575, 875, 115, 110, 135);

// running_gear: right_rear_upper_shock_mount - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(3185, 575, 875, 115, 110, 135);

// running_gear: right_front_shock_piston_rod - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(920, 520, 850, "z", 24, 280);

// running_gear: right_rear_shock_piston_rod - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3205, 520, 850, "z", 24, 280);

// running_gear: right_front_bump_stop - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(640, 495, 540, 115, 80, 72);

// running_gear: right_rear_bump_stop - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(2925, 495, 540, 115, 80, 72);

// chassis: transfer_case_crossmember - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(1710, 0, 500, 260, 940, 120);

// chassis: skid_plate_transfer_case - L2 underbody reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(1600, 0, 315, 520, 620, 42);

// running_gear: transfer_case - L2 underbody reference
color([0.247, 0.259, 0.271, 0.80])
  box_part(1640, 0, 575, 410, 360, 265);

// running_gear: gearbox_tail_housing - L2 underbody reference
color([0.247, 0.259, 0.271, 0.80])
  box_part(1325, 0, 610, 430, 300, 260);

// running_gear: front_prop_shaft - L2 underbody reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1120, 0, 465, "x", 82, 900);

// running_gear: rear_prop_shaft - L2 underbody reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2180, 0, 465, "x", 82, 1360);

// running_gear: front_diff_pumpkin - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, 0, 420, "y", 360, 300);

// running_gear: rear_diff_pumpkin - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, 0, 420, "y", 380, 320);

// running_gear: front_pinion_nose - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(920, 0, 430, "x", 145, 310);

// running_gear: rear_pinion_nose - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2780, 0, 430, "x", 145, 310);

// chassis: left_hand_drive_steering_box - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(535, -515, 610, 245, 175, 230);

// chassis: steering_box_left_frame_mount_plate - L2 bracket reference
color([0.176, 0.188, 0.200, 0.80])
  box_part(500, -445, 600, 295, 28, 260);

// running_gear: pitman_arm_left_hand_drive - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(675, -555, 565, "z", 62, 250);

// running_gear: front_drag_link_left_hand_drive - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(875, -555, 505, "x", 34, 620);

// running_gear: front_tie_rod - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, 0, 505, "y", 32, 1420);

// running_gear: steering_damper - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(905, -350, 480, "x", 58, 520);

// running_gear: front_left_steering_knuckle_arm - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(855, -690, 475, 150, 58, 60);

// running_gear: front_right_steering_knuckle_arm - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(855, 690, 475, 150, 58, 60);

// running_gear: front_left_brake_backing_plate - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, -750, 395, "y", 365, 55);

// running_gear: front_right_brake_backing_plate - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, 750, 395, "y", 365, 55);

// running_gear: front_left_leaf_spring_layer_1 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, -430, 305, 935, 78, 14);

// running_gear: front_left_leaf_spring_layer_2 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, -430, 323, 820, 78, 14);

// running_gear: front_left_leaf_spring_layer_3 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, -430, 341, 705, 78, 14);

// running_gear: front_left_u_bolt_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(670, -430, 405, "z", 24, 210);

// running_gear: front_left_u_bolt_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(800, -430, 405, "z", 24, 210);

// running_gear: front_right_leaf_spring_layer_1 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, 430, 305, 935, 78, 14);

// running_gear: front_right_leaf_spring_layer_2 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, 430, 323, 820, 78, 14);

// running_gear: front_right_leaf_spring_layer_3 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(215, 430, 341, 705, 78, 14);

// running_gear: front_right_u_bolt_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(670, 430, 405, "z", 24, 210);

// running_gear: front_right_u_bolt_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(800, 430, 405, "z", 24, 210);

// running_gear: rear_left_brake_backing_plate - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, -750, 395, "y", 365, 55);

// running_gear: rear_right_brake_backing_plate - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, 750, 395, "y", 365, 55);

// running_gear: rear_left_leaf_spring_layer_1 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, -430, 305, 935, 78, 14);

// running_gear: rear_left_leaf_spring_layer_2 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, -430, 323, 820, 78, 14);

// running_gear: rear_left_leaf_spring_layer_3 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, -430, 341, 705, 78, 14);

// running_gear: rear_left_u_bolt_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2955, -430, 405, "z", 24, 210);

// running_gear: rear_left_u_bolt_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3085, -430, 405, "z", 24, 210);

// running_gear: rear_right_leaf_spring_layer_1 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, 430, 305, 935, 78, 14);

// running_gear: rear_right_leaf_spring_layer_2 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, 430, 323, 820, 78, 14);

// running_gear: rear_right_leaf_spring_layer_3 - L2 visible-detail primitive
color([0.133, 0.133, 0.133, 0.80])
  box_part(2500, 430, 341, 705, 78, 14);

// running_gear: rear_right_u_bolt_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2955, 430, 405, "z", 24, 210);

// running_gear: rear_right_u_bolt_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3085, 430, 405, "z", 24, 210);

// running_gear: front_left_outer_rim_ring - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, -845, 395, "y", 455, 34);

// running_gear: front_left_inner_rim_shadow - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(735, -855, 395, "y", 315, 22);

// running_gear: front_left_valve_stem - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(865, -870, 540, "y", 22, 50);

// running_gear: front_left_lug_nut_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(827, -877, 395, "y", 32, 36);

// running_gear: front_left_lug_nut_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(781, -877, 474.674, "y", 32, 36);

// running_gear: front_left_lug_nut_3 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(689, -877, 474.674, "y", 32, 36);

// running_gear: front_left_lug_nut_4 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(643, -877, 395, "y", 32, 36);

// running_gear: front_left_lug_nut_5 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(689, -877, 315.326, "y", 32, 36);

// running_gear: front_left_lug_nut_6 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(781, -877, 315.326, "y", 32, 36);

// running_gear: front_right_outer_rim_ring - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(735, 845, 395, "y", 455, 34);

// running_gear: front_right_inner_rim_shadow - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(735, 855, 395, "y", 315, 22);

// running_gear: front_right_valve_stem - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(865, 870, 540, "y", 22, 50);

// running_gear: front_right_lug_nut_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(827, 877, 395, "y", 32, 36);

// running_gear: front_right_lug_nut_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(781, 877, 474.674, "y", 32, 36);

// running_gear: front_right_lug_nut_3 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(689, 877, 474.674, "y", 32, 36);

// running_gear: front_right_lug_nut_4 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(643, 877, 395, "y", 32, 36);

// running_gear: front_right_lug_nut_5 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(689, 877, 315.326, "y", 32, 36);

// running_gear: front_right_lug_nut_6 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(781, 877, 315.326, "y", 32, 36);

// running_gear: rear_left_outer_rim_ring - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, -845, 395, "y", 455, 34);

// running_gear: rear_left_inner_rim_shadow - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(3020, -855, 395, "y", 315, 22);

// running_gear: rear_left_valve_stem - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(3150, -870, 540, "y", 22, 50);

// running_gear: rear_left_lug_nut_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3112, -877, 395, "y", 32, 36);

// running_gear: rear_left_lug_nut_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3066, -877, 474.674, "y", 32, 36);

// running_gear: rear_left_lug_nut_3 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2974, -877, 474.674, "y", 32, 36);

// running_gear: rear_left_lug_nut_4 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2928, -877, 395, "y", 32, 36);

// running_gear: rear_left_lug_nut_5 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2974, -877, 315.326, "y", 32, 36);

// running_gear: rear_left_lug_nut_6 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3066, -877, 315.326, "y", 32, 36);

// running_gear: rear_right_outer_rim_ring - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, 845, 395, "y", 455, 34);

// running_gear: rear_right_inner_rim_shadow - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(3020, 855, 395, "y", 315, 22);

// running_gear: rear_right_valve_stem - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(3150, 870, 540, "y", 22, 50);

// running_gear: rear_right_lug_nut_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3112, 877, 395, "y", 32, 36);

// running_gear: rear_right_lug_nut_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3066, 877, 474.674, "y", 32, 36);

// running_gear: rear_right_lug_nut_3 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2974, 877, 474.674, "y", 32, 36);

// running_gear: rear_right_lug_nut_4 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2928, 877, 395, "y", 32, 36);

// running_gear: rear_right_lug_nut_5 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2974, 877, 315.326, "y", 32, 36);

// running_gear: rear_right_lug_nut_6 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3066, 877, 315.326, "y", 32, 36);

// brake_system: front_hard_line_left_frame_run - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1180, -338, 575, "x", 18, 1650);

// brake_system: rear_hard_line_left_frame_run - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2320, -338, 575, "x", 18, 1500);

// brake_system: rear_axle_brake_line - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3020, 0, 520, "y", 18, 1280);

// brake_system: parking_brake_front_cable - L2 routing reference
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1630, -145, 545, "x", 22, 650);

// brake_system: parking_brake_equalizer_bar - L3 specific item reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(2295, 0, 548, 175, 46, 24);

// brake_system: parking_brake_equalizer_pivot_pin - L3 specific item reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2380, 0, 548, "y", 26, 120);

// brake_system: left_rear_parking_brake_cable - L3 specific item reference
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(2685, -360, 535, "x", 22, 760);

// brake_system: left_parking_brake_clevis - L3 specific item reference
color([0.769, 0.604, 0.239, 0.80])
  box_part(3035, -520, 548, 66, 32, 34);

// brake_system: left_parking_brake_return_spring - L3 specific item reference
color([0.133, 0.133, 0.133, 0.80])
  cylinder_part(2945, -520, 602, "x", 34, 170);

// brake_system: left_parking_brake_cable_clip_1 - L3 specific item reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(2485, -430, 545, 38, 30, 34);

// brake_system: left_parking_brake_cable_clip_2 - L3 specific item reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(2805, -470, 545, 38, 30, 34);

// brake_system: right_rear_parking_brake_cable - L3 specific item reference
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(2685, 360, 535, "x", 22, 760);

// brake_system: right_parking_brake_clevis - L3 specific item reference
color([0.769, 0.604, 0.239, 0.80])
  box_part(3035, 520, 548, 66, 32, 34);

// brake_system: right_parking_brake_return_spring - L3 specific item reference
color([0.133, 0.133, 0.133, 0.80])
  cylinder_part(2945, 520, 602, "x", 34, 170);

// brake_system: right_parking_brake_cable_clip_1 - L3 specific item reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(2485, 430, 545, 38, 30, 34);

// brake_system: right_parking_brake_cable_clip_2 - L3 specific item reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(2805, 470, 545, 38, 30, 34);

// body: transmission_tunnel - L2 visible-detail primitive
color([0.812, 0.776, 0.667, 0.80])
  box_part(1250, 0, 660, 1100, 360, 235);

// body: rear_load_floor - L2 visible-detail primitive
color([0.812, 0.776, 0.667, 0.80])
  box_part(2060, 0, 690, 1180, 1230, 42);

// body: rear_floor_longitudinal_rib_1 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2050, -420, 740, 1230, 38, 42);

// body: rear_floor_longitudinal_rib_2 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2050, -210, 740, 1230, 38, 42);

// body: rear_floor_longitudinal_rib_3 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2050, 0, 740, 1230, 38, 42);

// body: rear_floor_longitudinal_rib_4 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2050, 210, 740, 1230, 38, 42);

// body: rear_floor_longitudinal_rib_5 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2050, 420, 740, 1230, 38, 42);

// body: floor_cross_pressing_1 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(980, 0, 735, 42, 1260, 34);

// body: floor_cross_pressing_2 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(1280, 0, 735, 42, 1260, 34);

// body: floor_cross_pressing_3 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(1730, 0, 735, 42, 1260, 34);

// body: floor_cross_pressing_4 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2140, 0, 735, 42, 1260, 34);

// body: floor_cross_pressing_5 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2570, 0, 735, 42, 1260, 34);

// body: floor_cross_pressing_6 - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(3020, 0, 735, 42, 1260, 34);

// body: left_front_wheel_arch_shadow - L2 visual aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(365, -735, 745, 740, 34, 405);

// body: left_rear_wheel_arch_shadow - L2 visual aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(2690, -735, 745, 690, 34, 410);

// body: left_rear_inner_wheel_tub - L2 panel reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2655, -505, 755, 750, 280, 385);

// body: left_tub_top_capping - L2 panel reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(1960, -805, 1322, 1530, 105, 58);

// body: left_door_outer_skin_lower_pressing - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(1235, -790, 845, 725, 34, 105);

// body: left_door_vertical_shut_gap_front - L2 aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(1130, -824, 780, 18, 28, 780);

// body: left_door_vertical_shut_gap_rear - L2 aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(1940, -824, 780, 18, 28, 780);

// body: left_mirror_arm - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(1210, -884, 1240, 210, 26, 32);

// body: left_door_mirror_head - L2 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  box_part(1405, -930, 1195, 135, 42, 110);

// body: left_fuel_or_body_plug_reference - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2935, -812, 1065, "y", 115, 28);

// body: right_front_wheel_arch_shadow - L2 visual aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(365, 735, 745, 740, 34, 405);

// body: right_rear_wheel_arch_shadow - L2 visual aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(2690, 735, 745, 690, 34, 410);

// body: right_rear_inner_wheel_tub - L2 panel reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(2655, 505, 755, 750, 280, 385);

// body: right_tub_top_capping - L2 panel reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(1960, 805, 1322, 1530, 105, 58);

// body: right_door_outer_skin_lower_pressing - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(1235, 790, 845, 725, 34, 105);

// body: right_door_vertical_shut_gap_front - L2 aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(1130, 824, 780, 18, 28, 780);

// body: right_door_vertical_shut_gap_rear - L2 aperture reference
color([0.114, 0.114, 0.114, 0.80])
  box_part(1940, 824, 780, 18, 28, 780);

// body: right_mirror_arm - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(1210, 884, 1240, 210, 26, 32);

// body: right_door_mirror_head - L2 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  box_part(1405, 930, 1195, 135, 42, 110);

// body: right_fuel_or_body_plug_reference - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2935, 812, 1065, "y", 115, 28);

// body: tailgate_hinge_or_chain_anchor_1 - L2 tailgate reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3450, -610, 800, "x", 54, 42);

// body: tailgate_hinge_or_chain_anchor_2 - L2 tailgate reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3450, -430, 1185, "x", 54, 42);

// body: tailgate_hinge_or_chain_anchor_3 - L2 tailgate reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3450, 430, 1185, "x", 54, 42);

// body: tailgate_hinge_or_chain_anchor_4 - L2 tailgate reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3450, 610, 800, "x", 54, 42);

// body: tailgate_lower_pressed_panel - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(3438, 0, 800, 38, 1190, 135);

// body: tailgate_upper_pressed_panel - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(3438, 0, 1115, 38, 1190, 120);

// body: rear_spare_tire - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(3605, 0, 1020, "x", 720, 230);

// body: rear_spare_wheel_rim - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3615, 0, 1020, "x", 385, 245);

// body: spare_wheel_carrier_vertical - L2 bracket reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(3520, 0, 800, 55, 72, 580);

// body: spare_wheel_carrier_crossbar - L2 bracket reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(3515, 0, 1015, 55, 560, 55);

// body: left_rear_tail_lamp - L2 visible-detail primitive
color([0.839, 0.278, 0.216, 0.80])
  cylinder_part(3470, -675, 930, "x", 98, 38);

// body: right_rear_tail_lamp - L2 visible-detail primitive
color([0.839, 0.278, 0.216, 0.80])
  cylinder_part(3470, 675, 930, "x", 98, 38);

// body: rear_license_plate - L2 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  box_part(3505, 0, 695, 24, 360, 170);

// front_detail: vertical_grille_slot_1 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(82, -300, 842, 26, 42, 230);

// front_detail: vertical_grille_slot_2 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(82, -200, 842, 26, 42, 230);

// front_detail: vertical_grille_slot_3 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(82, -100, 842, 26, 42, 230);

// front_detail: vertical_grille_slot_4 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(82, 0, 842, 26, 42, 230);

// front_detail: vertical_grille_slot_5 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(82, 100, 842, 26, 42, 230);

// front_detail: vertical_grille_slot_6 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(82, 200, 842, 26, 42, 230);

// front_detail: vertical_grille_slot_7 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(82, 300, 842, 26, 42, 230);

// front_detail: headlamp_bezel_left - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(80, -495, 985, "x", 270, 28);

// front_detail: side_marker_left - L2 visible-detail primitive
color([0.839, 0.278, 0.216, 0.80])
  cylinder_part(188, -683.1, 1005, "y", 82, 26);

// front_detail: headlamp_bezel_right - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(80, 495, 985, "x", 270, 28);

// front_detail: side_marker_right - L2 visible-detail primitive
color([0.839, 0.278, 0.216, 0.80])
  cylinder_part(188, 683.1, 1005, "y", 82, 26);

// front_detail: front_license_plate - L2 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  box_part(5, 0, 650, 22, 360, 170);

// front_detail: front_bumper_left_end_cap - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(40, -780, 525, 150, 115, 130);

// front_detail: front_bumper_right_end_cap - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(40, 780, 525, 150, 115, 130);

// body: hood_center_raised_rib - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(320, 0, 1277, 760, 180, 48);

// body: hood_left_outer_rib - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(330, -470, 1265, 730, 52, 38);

// body: hood_right_outer_rib - L2 panel rib reference
color([0.812, 0.776, 0.667, 0.80])
  box_part(330, 470, 1265, 730, 52, 38);

// body: left_hood_latch - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(810, -610, 1210, 88, 50, 58);

// body: left_cowl_vent_slot - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1020, -350, 1335, 150, 42, 26);

// body: left_windshield_outer_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1122, -548, 1370, 30, 55, 470);

// body: right_hood_latch - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(810, 610, 1210, 88, 50, 58);

// body: right_cowl_vent_slot - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1020, 350, 1335, 150, 42, 26);

// body: right_windshield_outer_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1122, 548, 1370, 30, 55, 470);

// body: windshield_top_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1122, 0, 1798, 30, 1320, 45);

// body: windshield_bottom_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1122, 0, 1360, 30, 1320, 42);

// hard_top: front_hardtop_roof_rib - L2 visible-detail primitive
color([0.945, 0.933, 0.894, 0.80])
  box_part(1290, 0, 1810, 45, 1510, 42);

// hard_top: front_left_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1290, -765, 1450, "z", 34, 640);

// hard_top: front_right_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1290, 765, 1450, "z", 34, 640);

// hard_top: middle_hardtop_roof_rib - L2 visible-detail primitive
color([0.945, 0.933, 0.894, 0.80])
  box_part(1960, 0, 1810, 45, 1510, 42);

// hard_top: middle_left_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1960, -765, 1450, "z", 34, 640);

// hard_top: middle_right_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1960, 765, 1450, "z", 34, 640);

// hard_top: rear_hardtop_roof_rib - L2 visible-detail primitive
color([0.945, 0.933, 0.894, 0.80])
  box_part(2640, 0, 1810, 45, 1510, 42);

// hard_top: rear_left_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2640, -765, 1450, "z", 34, 640);

// hard_top: rear_right_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2640, 765, 1450, "z", 34, 640);

// hard_top: tail_hardtop_roof_rib - L2 visible-detail primitive
color([0.945, 0.933, 0.894, 0.80])
  box_part(3300, 0, 1810, 45, 1510, 42);

// hard_top: tail_left_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3300, -765, 1450, "z", 34, 640);

// hard_top: tail_right_hardtop_vertical_frame - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3300, 765, 1450, "z", 34, 640);

// hard_top: left_hardtop_lower_retainer_rail - L2 bracket reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(1240, -830, 1288, 2200, 42, 46);

// hard_top: left_front_window_rubber_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1420, -842, 1435, 535, 28, 355);

// hard_top: left_rear_window_rubber_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2190, -842, 1435, 650, 28, 355);

// hard_top: left_hardtop_vertical_joint_1 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1320, -826, 1320, 22, 28, 570);

// hard_top: left_hardtop_vertical_joint_2 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1820, -826, 1320, 22, 28, 570);

// hard_top: left_hardtop_vertical_joint_3 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2500, -826, 1320, 22, 28, 570);

// hard_top: left_hardtop_vertical_joint_4 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3180, -826, 1320, 22, 28, 570);

// body: left_side_step_board - L2 visible-detail primitive
color([0.945, 0.933, 0.894, 0.80])
  box_part(1540, -865, 620, 1120, 210, 55);

// body: left_diesel_badge - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(2925, -822, 980, 120, 24, 42);

// hard_top: right_hardtop_lower_retainer_rail - L2 bracket reference
color([0.722, 0.722, 0.722, 0.80])
  box_part(1240, 830, 1288, 2200, 42, 46);

// hard_top: right_front_window_rubber_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1420, 842, 1435, 535, 28, 355);

// hard_top: right_rear_window_rubber_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2190, 842, 1435, 650, 28, 355);

// hard_top: right_hardtop_vertical_joint_1 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1320, 826, 1320, 22, 28, 570);

// hard_top: right_hardtop_vertical_joint_2 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1820, 826, 1320, 22, 28, 570);

// hard_top: right_hardtop_vertical_joint_3 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2500, 826, 1320, 22, 28, 570);

// hard_top: right_hardtop_vertical_joint_4 - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3180, 826, 1320, 22, 28, 570);

// body: right_side_step_board - L2 visible-detail primitive
color([0.945, 0.933, 0.894, 0.80])
  box_part(1540, 865, 620, 1120, 210, 55);

// body: right_diesel_badge - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(2925, 822, 980, 120, 24, 42);

// hard_top: rear_window_rubber_seal - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(3470, 0, 1460, 28, 850, 330);

// hard_top: rear_hardtop_window - L2 visible-detail primitive
color([0.435, 0.647, 0.722, 0.80])
  box_part(3485, 0, 1470, 18, 780, 275);

// hard_top: rear_corner_glass_or_seal_45 - L2 visible-detail primitive
color([0.435, 0.647, 0.722, 0.80])
  box_part(3500, -555, 1415, 28, 170, 300);

// hard_top: rear_corner_glass_or_seal_325 - L2 visible-detail primitive
color([0.435, 0.647, 0.722, 0.80])
  box_part(3500, -275, 1415, 28, 170, 300);

// hard_top: rear_corner_glass_or_seal_875 - L2 visible-detail primitive
color([0.435, 0.647, 0.722, 0.80])
  box_part(3500, 275, 1415, 28, 170, 300);

// hard_top: rear_corner_glass_or_seal_1155 - L2 visible-detail primitive
color([0.435, 0.647, 0.722, 0.80])
  box_part(3500, 555, 1415, 28, 170, 300);

// interior: dashboard_glovebox_door - L2 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  box_part(1212, 420, 1115, 35, 335, 150);

// interior: dash_instrument_cluster_plate - L2 visible-detail primitive
color([0.910, 0.910, 0.910, 0.80])
  box_part(1208, -420, 1128, 36, 330, 170);

// interior: dash_switch_knob_1 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, -535, 1050, "x", 34, 26);

// interior: dash_switch_knob_2 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, -480, 1050, "x", 34, 26);

// interior: dash_switch_knob_3 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, -425, 1050, "x", 34, 26);

// interior: dash_switch_knob_4 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, -370, 1050, "x", 34, 26);

// interior: dash_switch_knob_5 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, -315, 1050, "x", 34, 26);

// interior: heater_control_knob_1 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, 90, 1048, "x", 30, 24);

// interior: heater_control_knob_2 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, 155, 1048, "x", 30, 24);

// interior: heater_control_knob_3 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, 220, 1048, "x", 30, 24);

// interior: heater_control_knob_4 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1200, 285, 1048, "x", 30, 24);

// interior: steering_wheel_spoke_1 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(1216, -510, 1205, 34, 170, 18);

// interior: steering_wheel_spoke_2 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(1216, -420, 1205, 34, 170, 18);

// interior: steering_wheel_spoke_3 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(1216, -330, 1205, 34, 170, 18);

// interior: clutch_pedal_pad - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1340, -520, 705, 90, 45, 110);

// interior: clutch_pedal_arm - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1300, -520, 820, "z", 22, 240);

// interior: brake_pedal_pad - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1340, -440, 705, 90, 45, 110);

// interior: brake_pedal_arm - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1300, -440, 820, "z", 22, 240);

// interior: accelerator_pedal_pad - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1340, -350, 705, 90, 45, 110);

// interior: accelerator_pedal_arm - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1300, -350, 820, "z", 22, 240);

// interior: lhd_pedal_box_reinforcement - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1195, -465, 850, 95, 285, 250);

// interior: lhd_steering_column_dash_bracket - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1215, -420, 1040, 62, 210, 66);

// interior: steering_column_firewall_boot - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1142, -420, 1020, "x", 130, 48);

// interior: brake_pedal_pivot_bar - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1260, -440, 960, "y", 32, 180);

// interior: clutch_pedal_pivot_bar - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1260, -520, 960, "y", 32, 170);

// interior: accelerator_linkage_pivot - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1225, -325, 875, 52, 42, 125);

// interior: steering_column_indicator_stalk - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1225, -605, 1220, "y", 22, 165);

// interior: driver_side_floor_dimmer_switch - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1290, -650, 735, 70, 55, 34);

// interior: handbrake_lever - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1760, -250, 790, "z", 32, 360);

// interior: gearshift_knob - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1500, -35, 1160, "z", 86, 60);

// interior: transfer_case_knob - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(1580, -120, 1110, "z", 76, 55);

// interior: front_left_seat_left_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1515, -420, 675, 545, 36, 42);

// interior: front_left_seat_right_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1515, -720, 675, 545, 36, 42);

// interior: rear_left_seat_left_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(2350, -420, 675, 545, 36, 42);

// interior: rear_left_seat_right_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(2350, -720, 675, 545, 36, 42);

// interior: left_front_seat_belt_buckle - L2 visible-detail primitive
color([0.839, 0.278, 0.216, 0.80])
  box_part(1730, -90, 850, 62, 42, 145);

// interior: left_front_seat_back_seam - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1848, -310, 1080, 24, 390, 28);

// interior: left_front_floor_mat - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1350, -310, 723, 760, 500, 22);

// interior: front_right_seat_left_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1515, 420, 675, 545, 36, 42);

// interior: front_right_seat_right_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1515, 720, 675, 545, 36, 42);

// interior: rear_right_seat_left_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(2350, 420, 675, 545, 36, 42);

// interior: rear_right_seat_right_rail - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(2350, 720, 675, 545, 36, 42);

// interior: right_front_seat_belt_buckle - L2 visible-detail primitive
color([0.839, 0.278, 0.216, 0.80])
  box_part(1730, 90, 850, 62, 42, 145);

// interior: right_front_seat_back_seam - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1848, 310, 1080, 24, 390, 28);

// interior: right_front_floor_mat - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(1350, 310, 723, 760, 500, 22);

// interior: rear_floor_mat - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2220, 0, 748, 1050, 1020, 22);

// interior: rear_bench_seat_seam - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(2510, 0, 845, 610, 1010, 24);

// engine_bay: cooling_fan_hub - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(300, 0, 1010, "x", 135, 62);

// engine_bay: cooling_fan_blade_1 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(286, 210, 992, 38, 250, 36);

// engine_bay: cooling_fan_blade_2 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(286, 105, 1173.87, 38, 250, 36);

// engine_bay: cooling_fan_blade_3 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(286, -105, 1173.87, 38, 250, 36);

// engine_bay: cooling_fan_blade_4 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(286, -210, 992, 38, 250, 36);

// engine_bay: cooling_fan_blade_5 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(286, -105, 810.135, 38, 250, 36);

// engine_bay: cooling_fan_blade_6 - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(286, 105, 810.135, 38, 250, 36);

// engine_bay: crank_pulley - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(385, 0, 850, "x", 145, 60);

// engine_bay: water_pump_pulley - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(360, 0, 1010, "x", 125, 54);

// engine_bay: fan_belt_upper_run - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(350, 0, 1010, 26, 38, 270);

// engine_bay: fan_belt_lower_run - L2 visible-detail primitive
color([0.114, 0.114, 0.114, 0.80])
  box_part(385, 0, 850, 26, 38, 235);

// engine_bay: alternator_body - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(565, 325, 1010, "x", 190, 220);

// engine_bay: starter_motor - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(730, 265, 680, "x", 155, 310);

// engine_bay: intake_manifold - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  box_part(560, -260, 995, 460, 90, 115);

// engine_bay: exhaust_manifold - L2 visible-detail primitive
color([0.247, 0.259, 0.271, 0.80])
  box_part(575, 260, 900, 500, 95, 145);

// engine_bay: carburetor_body - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(745, -220, 1165, "z", 120, 170);

// engine_bay: round_air_cleaner_lid - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(760, -235, 1250, "z", 260, 68);

// engine_bay: brake_booster - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1075, -520, 1060, "x", 260, 145);

// engine_bay: master_cylinder - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(945, -520, 1060, "x", 92, 230);

// engine_bay: clutch_master_cylinder - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(945, -350, 1035, 210, 82, 76);

// engine_bay: lhd_firewall_pedal_box_outer_plate - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1112, -475, 895, 42, 350, 300);

// engine_bay: brake_booster_firewall_bracket - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(1110, -520, 1015, 48, 300, 250);

// engine_bay: brake_master_reservoir - L2 service datum
color([0.910, 0.910, 0.910, 0.80])
  cylinder_part(875, -520, 1165, "z", 110, 105);

// engine_bay: brake_master_reservoir_cap - L2 visible-detail primitive
color([0.769, 0.604, 0.239, 0.80])
  cylinder_part(875, -520, 1225, "z", 82, 24);

// engine_bay: brake_booster_vacuum_hose - L2 routing reference
color([0.114, 0.114, 0.114, 0.80])
  cylinder_part(820, -430, 1130, "x", 34, 470);

// engine_bay: clutch_master_reservoir_cap - L2 service datum
color([0.769, 0.604, 0.239, 0.80])
  cylinder_part(910, -350, 1130, "z", 70, 26);

// engine_bay: clutch_hydraulic_line_firewall_run - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(830, -350, 980, "x", 14, 520);

// engine_bay: steering_column_lower_firewall_shaft - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1010, -420, 980, "x", 44, 340);

// engine_bay: steering_column_lower_universal_joint - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(840, -430, 955, "x", 76, 58);

// engine_bay: steering_intermediate_shaft - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(690, -455, 850, "x", 40, 360);

// engine_bay: battery_case - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(570, 430, 765, 310, 205, 205);

// engine_bay: battery_positive_terminal - L2 service datum
color([0.839, 0.278, 0.216, 0.80])
  cylinder_part(622, 355, 985, "z", 34, 46);

// engine_bay: battery_negative_terminal - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(812, 505, 985, "z", 34, 46);

// engine_bay: positive_battery_cable_run - L2 routing reference
color([0.839, 0.278, 0.216, 0.80])
  cylinder_part(710, 405, 1015, "x", 24, 520);

// engine_bay: radiator_top_tank - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(205, 0, 1095, "y", 95, 1030);

// engine_bay: radiator_bottom_tank - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(205, 0, 720, "y", 85, 1030);

// engine_bay: radiator_cap - L2 visible-detail primitive
color([0.769, 0.604, 0.239, 0.80])
  cylinder_part(218, 260, 1155, "z", 54, 36);

// engine_bay: washer_bottle - L2 service datum
color([0.910, 0.910, 0.910, 0.80])
  box_part(795, 535, 850, 160, 105, 210);

// engine_bay: engine_bay_fuse_relay_board_reference - L2 packaging reference
color([0.839, 0.278, 0.216, 0.80])
  box_part(930, 610, 930, 240, 75, 220);

// engine_bay: dipstick_loop - L2 visible-detail primitive
color([0.769, 0.604, 0.239, 0.80])
  cylinder_part(840, 130, 1030, "z", 46, 28);

// fuel_system: rear_underfloor_fuel_tank - L2 underbody reference
color([0.310, 0.498, 0.333, 0.80])
  box_part(2870, 0, 405, 650, 930, 260);

// fuel_system: fuel_tank_retaining_strap_1 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(2780, 0, 555, 42, 980, 38);

// fuel_system: fuel_tank_retaining_strap_2 - L2 service datum
color([0.722, 0.722, 0.722, 0.80])
  box_part(3020, 0, 555, 42, 980, 38);

// fuel_system: fuel_filler_neck - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(3000, -690, 940, "z", 76, 410);

// fuel_system: fuel_line_frame_run - L2 routing reference
color([0.769, 0.604, 0.239, 0.80])
  cylinder_part(1880, 330, 560, "x", 16, 2070);

// exhaust: front_exhaust_pipe - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(870, 310, 520, "x", 68, 950);

// exhaust: centre_exhaust_pipe - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(1700, 330, 470, "x", 68, 1020);

// exhaust: rear_exhaust_pipe - L2 routing reference
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2750, 330, 470, "x", 62, 1220);

// exhaust: muffler_body - L2 visible-detail primitive
color([0.722, 0.722, 0.722, 0.80])
  cylinder_part(2260, 330, 465, "x", 250, 650);

// exhaust: exhaust_hanger_1 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(1020, 330, 590, 52, 58, 135);

// exhaust: exhaust_hanger_2 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(2180, 330, 590, 52, 58, 135);

// exhaust: exhaust_hanger_3 - L2 service datum
color([0.114, 0.114, 0.114, 0.80])
  box_part(3040, 330, 590, 52, 58, 135);

// datum: wheelbase_datum_line_left - measurement datum
color([0.486, 0.435, 0.796, 0.80])
  cylinder_part(1877.5, -925, 285, "x", 18, 2285);

// datum: wheelbase_datum_line_right - measurement datum
color([0.486, 0.435, 0.796, 0.80])
  cylinder_part(1877.5, 925, 285, "x", 18, 2285);

// datum: front_track_datum_line - measurement datum
color([0.486, 0.435, 0.796, 0.80])
  cylinder_part(735, 0, 260, "y", 18, 1410);

// datum: rear_track_datum_line - measurement datum
color([0.486, 0.435, 0.796, 0.80])
  cylinder_part(3020, 0, 260, "y", 18, 1410);
