// BUMP-60010 long bump stop model, front-left and rear
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

module chamfered_extrude(height, edge_chamfer = 0) {
  eps = 0.01;
  if (edge_chamfer <= 0) {
    linear_extrude(height = height, center = false)
      children();
  } else {
    union() {
      translate([0, 0, edge_chamfer])
        linear_extrude(height = height - (2 * edge_chamfer), center = false)
          children();

      hull() {
        translate([0, 0, 0])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
        translate([0, 0, edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
      }

      hull() {
        translate([0, 0, height - edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
        translate([0, 0, height - eps])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
      }
    }
  }
}

// Vehicle-measurement model:
// - Height is the known Toyota-family control.
// - The user will provide the one-piece flat metal backing/saddle with the
//   fabrication request. Use it as the plate outline, hole pattern, and bond
//   face pattern.
// - Flat plate footprint, bolt/stud pitch, hole/thread size, and strike offset
//   must be confirmed against the cleaned vehicle bracket and axle strike pad.
// - Default holes are visual placeholders in the flat steel plate, not through
//   the rubber.
// - This model is a first-article conversation shape, not a released mould.

module b_60010_long_measurement_model(
  free_height = 70,
  top_length = 46,
  top_width = 30,
  rubber_base_length = 70,
  rubber_base_width = 40,
  flat_plate_length = 82,
  flat_plate_width = 48,
  flat_plate_thickness = 4,
  plate_hole_pitch = 64,
  plate_hole_d = 10
) {
  union() {
    color("silver")
      difference() {
        translate([0, 0, -flat_plate_thickness])
          linear_extrude(height = flat_plate_thickness, center = false)
            rounded_rect_2d([flat_plate_length, flat_plate_width], 3);

        if (plate_hole_d > 0 && plate_hole_pitch > 0)
          for (x = [-plate_hole_pitch / 2, plate_hole_pitch / 2])
            translate([x, 0, -flat_plate_thickness - 1])
              cylinder(h = flat_plate_thickness + 2, d = plate_hole_d);
      }

    color("black")
      hull() {
        translate([0, 0, 0.5])
          linear_extrude(height = 1, center = false)
            rounded_rect_2d([rubber_base_length, rubber_base_width], 5);
        translate([0, 0, free_height - 1])
          linear_extrude(height = 1, center = false)
            rounded_rect_2d([top_length, top_width], 4);
      }
  }
}

b_60010_long_measurement_model();
