// BUMP-60010 rear pair bump stop model
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

module chamfered_extrude(height, edge_chamfer = 0) {
  eps = 0.01;
  if (edge_chamfer <= 0) {
    linear_extrude(height = height, center = false)
      children();
  } else {
    union() {
      translate([0, 0, edge_chamfer])
        linear_extrude(height = height - (2 * edge_chamfer), center = false)
          children();

      hull() {
        translate([0, 0, 0])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
        translate([0, 0, edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
      }

      hull() {
        translate([0, 0, height - edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
        translate([0, 0, height - eps])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
      }
    }
  }
}

// Vehicle-measurement model:
// - Height is the known Toyota-family control.
// - This is a rubber-only stretch-fit bolt-on stop. There is no steel saddle
//   or backing plate in the part.
// - Rubber base footprint, bolt/stud pitch, relaxed hole or slot size, and
//   strike offset must come from the cleaned vehicle bracket and axle strike pad.
// - Default holes are relaxed undersize visual placeholders so the rubber can
//   stretch over/around the bolts or studs during installation.
// - This model is a first-article conversation shape, not a released mould.

module b_60010_rear_pair_measurement_model(
  free_height = 70,
  top_length = 46,
  top_width = 30,
  rubber_base_length = 82,
  rubber_base_width = 48,
  bolt_hole_pitch = 64,
  relaxed_hole_d = 8.5,
  stretch_slot_extra = 0
) {
  difference() {
    color("black")
      hull() {
        translate([0, 0, 0.5])
          linear_extrude(height = 1, center = false)
            rounded_rect_2d([rubber_base_length, rubber_base_width], 5);
        translate([0, 0, free_height - 1])
          linear_extrude(height = 1, center = false)
            rounded_rect_2d([top_length, top_width], 4);
      }

    if (relaxed_hole_d > 0 && bolt_hole_pitch > 0)
      for (x = [-bolt_hole_pitch / 2, bolt_hole_pitch / 2])
        translate([x, 0, -1])
          if (stretch_slot_extra > 0)
            linear_extrude(height = free_height + 2, center = false)
              capsule_2d(relaxed_hole_d + stretch_slot_extra, relaxed_hole_d);
          else
            cylinder(h = free_height + 2, d = relaxed_hole_d);
  }
}

b_60010_rear_pair_measurement_model();
