// BUMP-60010 rear pair bump stop model
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

module chamfered_extrude(height, edge_chamfer = 0) {
  eps = 0.01;
  if (edge_chamfer <= 0) {
    linear_extrude(height = height, center = false)
      children();
  } else {
    union() {
      translate([0, 0, edge_chamfer])
        linear_extrude(height = height - (2 * edge_chamfer), center = false)
          children();

      hull() {
        translate([0, 0, 0])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
        translate([0, 0, edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
      }

      hull() {
        translate([0, 0, height - edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
        translate([0, 0, height - eps])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
      }
    }
  }
}

// Vehicle-measurement model:
// - Height is the known Toyota-family control.
// - May 29 removed samples now control the construction concept for both bump
//   stops: broad rounded/tapered rubber body, two through-holes in the rubber,
//   central fixture/channel interface, and flat strike area.
// - Final body footprint, through-hole pitch/diameter, fixture channel, and
//   strike offset must be confirmed from sample calipers, removed metal fixture,
//   cleaned vehicle bracket, and axle strike pad.
// - This model is a first-article conversation shape, not a released mould.

module b_60010_rear_pair_measurement_model(
  free_height = 70,
  top_length = 58,
  top_width = 32,
  rubber_base_length = 92,
  rubber_base_width = 54,
  rubber_hole_pitch = 64,
  rubber_hole_d = 12,
  fixture_channel_width = 20,
  fixture_channel_depth = 6
) {
  union() {
    color("black")
      difference() {
        hull() {
          translate([0, 0, 0.5])
            linear_extrude(height = 1, center = false)
              rounded_rect_2d([rubber_base_length, rubber_base_width], 10);
          translate([0, 0, free_height - 1])
            linear_extrude(height = 1, center = false)
              rounded_rect_2d([top_length, top_width], 6);
        }

        if (rubber_hole_d > 0 && rubber_hole_pitch > 0)
          for (x = [-rubber_hole_pitch / 2, rubber_hole_pitch / 2])
            translate([x, 0, -1])
              cylinder(h = free_height + 2, d = rubber_hole_d);
      }

    color("silver")
      translate([0, 0, free_height - fixture_channel_depth / 2])
        cube([fixture_channel_width, rubber_base_width + 4, fixture_channel_depth], center = true);
  }
}

b_60010_rear_pair_measurement_model();
