// BM-ISO-SM main body isolator pad, small stations
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

module chamfered_extrude(height, edge_chamfer = 0) {
  eps = 0.01;
  if (edge_chamfer <= 0) {
    linear_extrude(height = height, center = false)
      children();
  } else {
    union() {
      translate([0, 0, edge_chamfer])
        linear_extrude(height = height - (2 * edge_chamfer), center = false)
          children();

      hull() {
        translate([0, 0, 0])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
        translate([0, 0, edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
      }

      hull() {
        translate([0, 0, height - edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
        translate([0, 0, height - eps])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
      }
    }
  }
}

// Current order basis:
// - Square solid pad 70 x 70 x 22.
// - 3D envelope is length x width x height; plan corner radius 1.5 mm.
// - Top and bottom perimeter edge break/chamfer is modelled at 1.0 mm by default.
// - Production bore is 18.0 mm for the Toyota 90560-12009 style body-mount spacer.
// - Toyota 90560-12009 is the best release basis: 48.1 mm spacer length, six sleeves.
// - Production release uses hole_d = 18.0; hole_d = 0 is a non-release CAD override.

module bm_iso_sm_square_pad(
  pad_size = 70,
  pad_height = 22,
  corner_r = 1.5,
  edge_chamfer = 1.0,
  hole_d = 18.0,
  center_mark = true
) {
  difference() {
    chamfered_extrude(height = pad_height, edge_chamfer = edge_chamfer)
      rounded_rect_2d([pad_size, pad_size], corner_r);

    if (hole_d > 0)
      translate([0, 0, -1])
        cylinder(h = pad_height + 2, d = hole_d);

    if (hole_d == 0 && center_mark)
      translate([0, 0, pad_height - 0.8])
        cylinder(h = 1.0, d = 4.0);
  }
}

bm_iso_sm_square_pad();
