// BM-ISO-LG main body isolator pad, large stations
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

// Current order basis:
// - Square solid pad 80 x 80 x 24.
// - Production bore is 18.0 mm for the Toyota 90560-12009 style body-mount spacer.
// - Toyota 90560-12009 is the best release basis: 48.1 mm spacer length, six sleeves.
// - Production release uses hole_d = 18.0; hole_d = 0 is a non-release CAD override.

module bm_iso_lg_square_pad(
  pad_size = 80,
  pad_height = 24,
  corner_r = 1.5,
  edge_chamfer = 0.0,
  hole_d = 18.0,
  center_mark = true
) {
  difference() {
    linear_extrude(height = pad_height, center = false)
      rounded_rect_2d([pad_size, pad_size], corner_r);

    if (hole_d > 0)
      translate([0, 0, -1])
        cylinder(h = pad_height + 2, d = hole_d);

    if (hole_d == 0 && center_mark)
      translate([0, 0, pad_height - 0.8])
        cylinder(h = 1.0, d = 4.0);
  }
}

bm_iso_lg_square_pad();
