// EXH-HGR-90917 teardrop exhaust cushion
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

module chamfered_extrude(height, edge_chamfer = 0) {
  eps = 0.01;
  if (edge_chamfer <= 0) {
    linear_extrude(height = height, center = false)
      children();
  } else {
    union() {
      translate([0, 0, edge_chamfer])
        linear_extrude(height = height - (2 * edge_chamfer), center = false)
          children();

      hull() {
        translate([0, 0, 0])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
        translate([0, 0, edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
      }

      hull() {
        translate([0, 0, height - edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
        translate([0, 0, height - eps])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
      }
    }
  }
}

// Hold-only model:
// - Toyota 90917-08004 is a part-family lead, not final geometry release.
// - Use this only as a conversation model until an intact sample or installed
//   support-point measurements release side profile and reinforcement detail.

module teardrop_outer_2d() {
  translate([-24, -42])
    polygon(points = [
    [24, 0],
    [31.5, 1.2],
    [38.1, 4.8],
    [43.2, 10],
    [46.8, 16.5],
    [48, 24],
    [44.8, 38.4],
    [38, 50],
    [38, 70],
    [32, 84],
    [16, 84],
    [10, 70],
    [10, 50],
    [3.2, 38.4],
    [0, 24],
    [1.2, 16.5],
    [4.8, 10],
    [9.9, 4.8],
    [16.5, 1.2]
    ]);
}

module exh_hgr_90917_teardrop_cushion(
  thickness = 22,
  top_hole_d = 9,
  lower_slot = [16, 22],
  boss_size = [36, 42],
  boss_depth = 1.0
) {
  difference() {
    linear_extrude(height = thickness, center = false)
      teardrop_outer_2d();

    translate([0, 31, -1])
      cylinder(h = thickness + 2, d = top_hole_d);

    translate([0, -13, -1])
      rotate([0, 0, 90])
        linear_extrude(height = thickness + 2, center = false)
          capsule_2d(lower_slot[1], lower_slot[0]);

    if (boss_depth > 0)
      translate([0, -13, thickness - boss_depth])
        rotate([0, 0, 90])
          linear_extrude(height = boss_depth + 0.2, center = false)
            capsule_2d(boss_size[1], boss_size[0]);
  }
}

exh_hgr_90917_teardrop_cushion();
