// FS-OVAL front support two-hole isolator pad
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

// Current order basis:
// - Overall capsule 96 x 64 x 15.
// - Two 12 mm holes on 64 mm centres.
// - relief_depth is a model option because the old part must prove whether the
//   rectangular relief is functional, blind, through-cut, or only washer imprint.

module fs_oval_front_support_pad(
  length = 96,
  width = 64,
  thickness = 15,
  hole_d = 12,
  hole_spacing = 64,
  relief_size = [36, 18],
  relief_r = 3,
  relief_depth = 0,
  insert_mark_d = 29,
  insert_mark_depth = 0.5
) {
  difference() {
    linear_extrude(height = thickness, center = false)
      capsule_2d(length, width);

    for (x = [-hole_spacing / 2, hole_spacing / 2])
      translate([x, 0, -1])
        cylinder(h = thickness + 2, d = hole_d);

    if (relief_depth > 0)
      translate([0, 0, thickness - relief_depth])
        linear_extrude(height = relief_depth + 0.2, center = false)
          rounded_rect_2d(relief_size, relief_r);

    if (insert_mark_depth > 0)
      translate([-hole_spacing / 2, 0, thickness - insert_mark_depth])
        cylinder(h = insert_mark_depth + 0.2, d = insert_mark_d);
  }
}

fs_oval_front_support_pad();
