// FS-STRIP-L underfloor body-support strip liner
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

// Current order basis:
// - Plain rubber strip 165 x 38 x 8.
// - No holes by default; steel retainer slots belong to the separate retainer
//   unless the actual old rubber proves the rubber itself was pierced.

module fs_strip_l_plain_strip(
  strip_length = 165,
  strip_width = 38,
  strip_thickness = 8,
  corner_r = 1.5,
  hole_d = 0,
  hole_centres = [-62.5, 62.5]
) {
  difference() {
    linear_extrude(height = strip_thickness, center = false)
      rounded_rect_2d([strip_length, strip_width], corner_r);

    if (hole_d > 0)
      for (x = hole_centres)
        translate([x, 0, -1])
          cylinder(h = strip_thickness + 2, d = hole_d);
  }
}

fs_strip_l_plain_strip();
