// J40 rubber model master
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {
  hull() {
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }
}

module capsule_2d(length, width) {
  hull() {
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }
}

module chamfered_extrude(height, edge_chamfer = 0) {
  eps = 0.01;
  if (edge_chamfer <= 0) {
    linear_extrude(height = height, center = false)
      children();
  } else {
    union() {
      translate([0, 0, edge_chamfer])
        linear_extrude(height = height - (2 * edge_chamfer), center = false)
          children();

      hull() {
        translate([0, 0, 0])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
        translate([0, 0, edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
      }

      hull() {
        translate([0, 0, height - edge_chamfer])
          linear_extrude(height = eps, center = false)
            children();
        translate([0, 0, height - eps])
          linear_extrude(height = eps, center = false)
            offset(delta = -edge_chamfer)
              children();
      }
    }
  }
}
use <bm_iso_sm_square_pad.scad>;
use <bm_iso_lg_square_pad.scad>;
use <fs_oval_front_support_pad.scad>;
use <fs_strip_l_plain_strip.scad>;
use <fs_strip_r_plain_strip.scad>;
use <b_60010_long_measurement_model.scad>;
use <b_60020_short_measurement_model.scad>;
use <b_60010_rear_pair_measurement_model.scad>;
use <exh_hgr_90917_teardrop_cushion.scad>;
// Render one part by uncommenting a call below.
// Body pads now default to the released 18.0 mm bore for Toyota 90560-12009 style spacers.

// bm_iso_sm_square_pad();
// bm_iso_lg_square_pad();
// fs_oval_front_support_pad(relief_depth = 0);
// fs_strip_l_plain_strip(hole_d = 0);
// fs_strip_r_plain_strip(hole_d = 0);
// b_60010_long_measurement_model();
// b_60020_short_measurement_model();
// b_60010_rear_pair_measurement_model();
// exh_hgr_90917_teardrop_cushion();
