from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "data" / "manual" / "fabrication" / "rubber_recreation_rev_a" / "models_3d"


@dataclass(frozen=True)
class ModelFile:
    part_id: str
    filename: str
    title: str
    quantity: str
    release_status: str
    controls: str
    old_part_questions: str


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="ascii")


def header(title: str) -> str:
    return f"""
// {title}
// J40 rubber recreation 3D model, units: millimetres.
// Generated by tools/generate_rubber_recreation_3d_models.py.
// OpenSCAD is the source model; export STL only after release parameters are set.

$fn = 64;

module rounded_rect_2d(size, r) {{
  hull() {{
    translate([-(size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r), -(size[1] / 2 - r)]) circle(r = r);
    translate([ (size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
    translate([-(size[0] / 2 - r),  (size[1] / 2 - r)]) circle(r = r);
  }}
}}

module capsule_2d(length, width) {{
  hull() {{
    translate([-(length - width) / 2, 0]) circle(d = width);
    translate([ (length - width) / 2, 0]) circle(d = width);
  }}
}}
"""


def body_pad_scad(part_id: str, title: str, size: float, height: float, qty: str) -> tuple[ModelFile, str]:
    filename = f"{part_id.lower().replace('-', '_')}_square_pad.scad"
    text = (
        header(title)
        + f"""
// Current order basis:
// - Square solid pad {size:g} x {size:g} x {height:g}.
// - hole_d defaults to 0 because the steel crush-sleeve OD is not released yet.
// - After sleeve measurement, set hole_d = sleeve_od + 0.5 to 1.0 mm.
// - Set center_mark = true for an undrilled pad with a shallow centre mark.

module {part_id.lower().replace('-', '_')}_square_pad(
  pad_size = {size:g},
  pad_height = {height:g},
  corner_r = 1.5,
  edge_chamfer = 0.0,
  hole_d = 0,
  center_mark = true
) {{
  difference() {{
    linear_extrude(height = pad_height, center = false)
      rounded_rect_2d([pad_size, pad_size], corner_r);

    if (hole_d > 0)
      translate([0, 0, -1])
        cylinder(h = pad_height + 2, d = hole_d);

    if (hole_d == 0 && center_mark)
      translate([0, 0, pad_height - 0.8])
        cylinder(h = 1.0, d = 4.0);
  }}
}}

{part_id.lower().replace('-', '_')}_square_pad();
"""
    )
    model = ModelFile(
        part_id=part_id,
        filename=filename,
        title=title,
        quantity=qty,
        release_status="quote-ready envelope; final bore held until sleeve OD is measured",
        controls=f"{size:g} x {size:g} x {height:g} mm square pad; optional hole_d parameter",
        old_part_questions=(
            "Measure old sleeve OD/ID/length, old rubber centre-hole diameter, whether the hole is centred or offset, "
            "top/bottom washer imprint diameter, and whether the old stack was one-piece or split."
        ),
    )
    return model, text


def fs_oval_scad() -> tuple[ModelFile, str]:
    filename = "fs_oval_front_support_pad.scad"
    text = (
        header("FS-OVAL front support two-hole isolator pad")
        + """
// Current order basis:
// - Overall capsule 96 x 64 x 15.
// - Two 12 mm holes on 64 mm centres.
// - relief_depth is a model option because the old part must prove whether the
//   rectangular relief is functional, blind, through-cut, or only washer imprint.

module fs_oval_front_support_pad(
  length = 96,
  width = 64,
  thickness = 15,
  hole_d = 12,
  hole_spacing = 64,
  relief_size = [36, 18],
  relief_r = 3,
  relief_depth = 0,
  insert_mark_d = 29,
  insert_mark_depth = 0.5
) {
  difference() {
    linear_extrude(height = thickness, center = false)
      capsule_2d(length, width);

    for (x = [-hole_spacing / 2, hole_spacing / 2])
      translate([x, 0, -1])
        cylinder(h = thickness + 2, d = hole_d);

    if (relief_depth > 0)
      translate([0, 0, thickness - relief_depth])
        linear_extrude(height = relief_depth + 0.2, center = false)
          rounded_rect_2d(relief_size, relief_r);

    if (insert_mark_depth > 0)
      translate([-hole_spacing / 2, 0, thickness - insert_mark_depth])
        cylinder(h = insert_mark_depth + 0.2, d = insert_mark_d);
  }
}

fs_oval_front_support_pad();
"""
    )
    model = ModelFile(
        part_id="FS-OVAL",
        filename=filename,
        title="FS-OVAL front support two-hole isolator pad",
        quantity="2",
        release_status="first-article model; relief/insert construction still sample-controlled",
        controls="96 x 64 x 15 mm capsule; two 12 mm holes at 64 mm centres; optional 36 x 18 x relief_depth pocket",
        old_part_questions=(
            "Confirm hole centre spacing, hole diameter, thickness, insert/boss OD, whether insert is bonded or loose, "
            "and whether the 36 x 18 relief is real or just deformation."
        ),
    )
    return model, text


def strip_scad(part_id: str, side: str) -> tuple[ModelFile, str]:
    filename = f"{part_id.lower().replace('-', '_')}_plain_strip.scad"
    module_name = f"{part_id.lower().replace('-', '_')}_plain_strip"
    text = (
        header(f"{part_id} underfloor body-support strip liner")
        + f"""
// Current order basis:
// - Plain rubber strip 165 x 38 x 8.
// - No holes by default; steel retainer slots belong to the separate retainer
//   unless the actual old rubber proves the rubber itself was pierced.

module {module_name}(
  strip_length = 165,
  strip_width = 38,
  strip_thickness = 8,
  corner_r = 1.5,
  hole_d = 0,
  hole_centres = [-62.5, 62.5]
) {{
  difference() {{
    linear_extrude(height = strip_thickness, center = false)
      rounded_rect_2d([strip_length, strip_width], corner_r);

    if (hole_d > 0)
      for (x = hole_centres)
        translate([x, 0, -1])
          cylinder(h = strip_thickness + 2, d = hole_d);
  }}
}}

{module_name}();
"""
    )
    model = ModelFile(
        part_id=part_id,
        filename=filename,
        title=f"{part_id} underfloor body-support strip liner {side}",
        quantity="1",
        release_status="first-article plain strip; local trim/holes only after dry-fit proves them",
        controls="165 x 38 x 8 mm plain strip; optional hole_d parameter held at 0 by default",
        old_part_questions=(
            "Check whether old rubber has any real pierced holes or only retainer marks, whether ends are square or trimmed, "
            "actual thickness, and whether left/right are identical."
        ),
    )
    return model, text


def exhaust_scad() -> tuple[ModelFile, str]:
    filename = "exh_hgr_90917_teardrop_cushion.scad"
    points = [
        [24.0, 0.0],
        [31.5, 1.2],
        [38.1, 4.8],
        [43.2, 10.0],
        [46.8, 16.5],
        [48.0, 24.0],
        [44.8, 38.4],
        [38.0, 50.0],
        [38.0, 70.0],
        [32.0, 84.0],
        [16.0, 84.0],
        [10.0, 70.0],
        [10.0, 50.0],
        [3.2, 38.4],
        [0.0, 24.0],
        [1.2, 16.5],
        [4.8, 10.0],
        [9.9, 4.8],
        [16.5, 1.2],
    ]
    point_text = ",\n    ".join(f"[{x:g}, {y:g}]" for x, y in points)
    text = (
        header("EXH-HGR-90917 teardrop exhaust cushion")
        + f"""
// Hold-only model:
// - Toyota 90917-08004 is a part-family lead, not final geometry release.
// - Use this only as a conversation model until an intact sample or installed
//   support-point measurements release side profile and reinforcement detail.

module teardrop_outer_2d() {{
  translate([-24, -42])
    polygon(points = [
    {point_text}
    ]);
}}

module exh_hgr_90917_teardrop_cushion(
  thickness = 22,
  top_hole_d = 9,
  lower_slot = [16, 22],
  boss_size = [36, 42],
  boss_depth = 1.0
) {{
  difference() {{
    linear_extrude(height = thickness, center = false)
      teardrop_outer_2d();

    translate([0, 31, -1])
      cylinder(h = thickness + 2, d = top_hole_d);

    translate([0, -13, -1])
      rotate([0, 0, 90])
        linear_extrude(height = thickness + 2, center = false)
          capsule_2d(lower_slot[1], lower_slot[0]);

    if (boss_depth > 0)
      translate([0, -13, thickness - boss_depth])
        rotate([0, 0, 90])
          linear_extrude(height = boss_depth + 0.2, center = false)
            capsule_2d(boss_size[1], boss_size[0]);
  }}
}}

exh_hgr_90917_teardrop_cushion();
"""
    )
    model = ModelFile(
        part_id="EXH-HGR-90917",
        filename=filename,
        title="EXH-HGR-90917 teardrop exhaust cushion",
        quantity="hold",
        release_status="hold-only; sample or installed support-point geometry required",
        controls="nominal 48 x 86 x 22 mm teardrop; 9 mm top hole; 16 x 22 lower slot",
        old_part_questions=(
            "If an old hanger exists, measure thickness, top hole, lower slot, side profile, reinforcement/insert, and installed pin/bracket spacing."
        ),
    )
    return model, text


def bump_stop_scad(part_id: str, title: str, height: float, qty: str) -> tuple[ModelFile, str]:
    filename = f"{part_id.lower().replace('-', '_')}_measurement_model.scad"
    module_name = f"{part_id.lower().replace('-', '_')}_measurement_model"
    text = (
        header(title)
        + f"""
// Vehicle-measurement model:
// - Height is the known Toyota-family control.
// - Saddle length/width, bolt pitch, bolt diameter, and strike offset must come
//   from the cleaned vehicle bracket and axle strike pad.
// - This model is a first-article conversation shape, not a released mould.

module {module_name}(
  free_height = {height:g},
  saddle_length = 90,
  saddle_width = 44,
  saddle_thickness = 4,
  bolt_pitch = 64,
  bolt_d = 10,
  top_length = 46,
  top_width = 30,
  rubber_base_length = 70,
  rubber_base_width = 40
) {{
  color("silver")
    difference() {{
      translate([0, 0, saddle_thickness / 2])
        cube([saddle_length, saddle_width, saddle_thickness], center = true);
      for (x = [-bolt_pitch / 2, bolt_pitch / 2])
        translate([x, 0, -1])
          cylinder(h = saddle_thickness + 2, d = bolt_d);
    }}

  color("black")
    translate([0, 0, saddle_thickness])
      hull() {{
        translate([0, 0, 0.5])
          linear_extrude(height = 1, center = false)
            rounded_rect_2d([rubber_base_length, rubber_base_width], 5);
        translate([0, 0, free_height - saddle_thickness - 1])
          linear_extrude(height = 1, center = false)
            rounded_rect_2d([top_length, top_width], 4);
      }}
}}

{module_name}();
"""
    )
    model = ModelFile(
        part_id=part_id,
        filename=filename,
        title=title,
        quantity=qty,
        release_status="measurement model only; bracket dimensions and strike offset required before mould release",
        controls=f"{height:g} mm free height known; saddle/base/bolt/strike geometry vehicle-controlled",
        old_part_questions=(
            "Do not use decayed rubber as the master. Measure bracket landing length/width, bolt pitch, bolt/hole size, strike-pad offset, "
            "loaded gap, and safe near-full-bump clearance."
        ),
    )
    return model, text


def write_master_scad(files: list[ModelFile]) -> None:
    includes = "\n".join(f'use <{model.filename}>;' for model in files)
    body = """
// Render one part by uncommenting a call below.
// Keep body pads with hole_d = 0 until sleeve OD is known.

// bm_iso_sm_square_pad(hole_d = 0);
// bm_iso_lg_square_pad(hole_d = 0);
// fs_oval_front_support_pad(relief_depth = 0);
// fs_strip_l_plain_strip(hole_d = 0);
// fs_strip_r_plain_strip(hole_d = 0);
// b_60010_long_measurement_model();
// b_60020_short_measurement_model();
// b_60010_rear_pair_measurement_model();
// exh_hgr_90917_teardrop_cushion();
"""
    write(OUT_DIR / "j40_rubber_models_master.scad", header("J40 rubber model master") + includes + body)


def write_manifest(files: list[ModelFile]) -> None:
    with (OUT_DIR / "model_manifest.csv").open("w", newline="", encoding="ascii") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "part_id",
                "filename",
                "title",
                "quantity",
                "release_status",
                "controls",
                "old_part_questions",
            ],
        )
        writer.writeheader()
        for model in files:
            writer.writerow(model.__dict__)


def write_questions(files: list[ModelFile]) -> None:
    rows = "\n".join(
        f"- `{model.part_id}`: {model.old_part_questions}" for model in files
    )
    text = f"""
# Old-Rubber Checks For 3D Model Closure

These checks are only needed when we are ready to release drilled holes, trim,
or mould details. The OpenSCAD files keep uncertain features as parameters.

## Why The Main Body Pads Are Undrilled

The main body pads are undrilled in the quote model because the rubber hole is
not the clamping feature. The bolt should clamp through a steel crush sleeve,
and the rubber hole only needs to clear that sleeve cleanly. The final bore is:

`final rubber hole = measured sleeve OD + 0.5 to 1.0 mm`

If the pad is drilled before the sleeve OD is known, a too-small hole can tear or
grab the sleeve, and a too-large hole can let the stack wander. A centre mark is
safe for quote/first article; final drilling is safe after the sleeve OD and
stack height are confirmed.

## Checks

{rows}
"""
    write(OUT_DIR / "old_rubber_checks.md", text)


def write_readme(files: list[ModelFile]) -> None:
    file_rows = "\n".join(
        f"- `{model.filename}` - `{model.part_id}` {model.title}; {model.release_status}"
        for model in files
    )
    text = f"""
# J40 Rubber Recreation 3D Models

This folder contains parametric OpenSCAD models for the current Longman rubber
order and the related hold-only bump-stop/exhaust reference shapes.

Use these files as 3D conversation and first-article controls. They do not
replace the 2D DXF/SVG/PDF pack or the CSV release gates.

## Files

- `j40_rubber_models_master.scad` - includes all individual models.
- `model_manifest.csv` - model index, release status, and open old-part checks.
- `old_rubber_checks.md` - what to inspect on the original parts if needed.
{file_rows}

## Critical Release Rules

- `BM-ISO-SM` and `BM-ISO-LG` default to `hole_d = 0`; set `hole_d` only after
  the crush-sleeve OD is measured.
- `FS-OVAL` has optional `relief_depth`; the old part must prove whether the
  relief is real, blind, through-cut, or only deformation.
- `FS-STRIP-L/R` default to no holes; retainer slots are separate steel detail
  unless the old rubber proves the rubber itself was pierced.
- Bump-stop models are measurement placeholders. Free height is known, but base,
  bolt, saddle, and strike geometry must come from the vehicle.
- The exhaust hanger model is hold-only until a sample or installed support
  measurements release thickness, side profile, and reinforcement detail.
"""
    write(OUT_DIR / "README.md", text)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    generated: list[ModelFile] = []
    specs = [
        body_pad_scad("BM-ISO-SM", "BM-ISO-SM main body isolator pad, small stations", 70, 22, "10 plus 2 spares"),
        body_pad_scad("BM-ISO-LG", "BM-ISO-LG main body isolator pad, large stations", 80, 24, "2 plus 1 spare"),
        fs_oval_scad(),
        strip_scad("FS-STRIP-L", "left"),
        strip_scad("FS-STRIP-R", "right"),
        bump_stop_scad("B-60010-LONG", "BUMP-60010 long bump stop model, front-left and rear", 70, "3"),
        bump_stop_scad("B-60020-SHORT", "BUMP-60020 short right-front bump stop model", 60, "1"),
        bump_stop_scad("B-60010-REAR-PAIR", "BUMP-60010 rear pair bump stop model", 70, "2"),
        exhaust_scad(),
    ]
    for model, text in specs:
        generated.append(model)
        write(OUT_DIR / model.filename, text)
    write_master_scad(generated)
    write_manifest(generated)
    write_questions(generated)
    write_readme(generated)
    print(f"Wrote 3D rubber models: {OUT_DIR}")
    print(f"Models: {len(generated)}")


if __name__ == "__main__":
    main()
